'use strict';
const key='maxmal-ui-studio-content-v1';
const id=new URLSearchParams(location.search).get('work');
const root=document.querySelector('#preview');
const el=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
function load(){try{return JSON.parse(localStorage.getItem(key));}catch{return null;}}
function update(fn){const data=load();const work=data?.works?.find(w=>w.id===id);if(!work)return;fn(work);try{localStorage.setItem(key,JSON.stringify(data));}catch{root.append(el('p','浏览器未能保存更改'));}}
function renderPreview(){root.replaceChildren();const data=load();const work=data?.works?.find(w=>w.id===id);if(!work){root.append(el('p','作品暂不可用，请在主工作台重新选择。'));return;}document.title=work.title;root.append(el('h1',work.title),el('p',work.description));if(work.kind==='notes'){const area=el('textarea');area.value=work.notes||'';area.setAttribute('aria-label','灵感便签');area.oninput=()=>update(w=>w.notes=area.value);root.append(area);}else{const form=el('form'),input=el('input');input.type='text';input.placeholder='添加一件想做的事';input.setAttribute('aria-label','新的待办');const add=el('button','添加');add.type='submit';form.append(input,add);form.onsubmit=e=>{e.preventDefault();if(input.value.trim()){update(w=>w.items.push({text:input.value.trim(),done:false}));renderPreview();}};root.append(form);(work.items||[]).forEach((item,i)=>{const row=el('label');row.className=item.done?'done':'';const check=el('input');check.type='checkbox';check.checked=item.done;check.onchange=()=>{update(w=>w.items[i].done=check.checked);renderPreview();};row.append(check,el('span',item.text));const remove=el('button','×');remove.type='button';remove.setAttribute('aria-label','删除 '+item.text);remove.onclick=e=>{e.preventDefault();update(w=>w.items.splice(i,1));renderPreview();};row.append(remove);root.append(row);});}root.append(el('small','本地应用预览'));}
window.addEventListener('storage',e=>{if(e.key===key)renderPreview();});renderPreview();
