'use strict';
const $ = s => document.querySelector(s);
const icons = {
panel:'M4 4h16v16H4z M9 4v16', 'arrow-left':'m12 5-7 7 7 7 M5 12h15', 'arrow-right':'m12 5 7 7-7 7 M4 12h15',chevron:'m7 10 5 5 5-5',search:'M10 18a8 8 0 1 0 0-16 8 8 0 0 0 0 16 M16 16l5 5',bell:'M5 17h14l-2-3V9a5 5 0 0 0-10 0v5z M10 20h4',edit:'M13 4H6a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-7 M12 13l-1-4 8-8 3 3-8 8z',branch:'M6 6v12 M18 6v4c0 4-12 0-12 4 M6 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4 M6 18a2 2 0 1 0 0 4 2 2 0 0 0 0-4 M18 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4',grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 6v6l-3 3',plugin:'M12 20a8 8 0 1 1 8-8c0 5-6 5-6 1V7 M14 10c-5-5-9 3-4 5 2 1 4-1 4-3 M12 20h7', 'circle-plus':'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 8v8 M8 12h8',plus:'M12 4v16 M4 12h16',wave:'M3 10v4 M7 5v14 M11 8v8 M15 3v18 M19 7v10 M23 10v4',help:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M9 8c1-3 7-2 6 1-1 2-3 1-3 5 M12 17v.1',folder:'M3 7V5h6l3 2h9v13H3z M3 10h18',hand:'M7 13V8c0-2 3-2 3 0V4c0-2 3-2 3 0v4-3c0-2 3-2 3 0v4-2c0-2 3-2 3 0v7c0 10-11 11-14 4l-2-4c-1-3 2-4 4-1z',mic:'M9 5a3 3 0 0 1 6 0v7a3 3 0 0 1-6 0z M5 10v2a7 7 0 0 0 14 0v-2 M12 19v3 M9 22h6',globe:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M3 12h18 M12 3c-6 6-6 12 0 18 6-6 6-12 0-18',terminal:'M4 4h16v16H4z m4 5 3 3-3 3 m6 0h3',expand:'M8 3H3v5 M16 3h5v5 M3 16v5h5 M21 16v5h-5',close:'m6 6 12 12 M6 18 18 6',telescope:'m3 9 13-5 3 6-13 5z M16 4l3-1 3 8-3 1 M10 14l-3 7 M12 13l4 8',hammer:'m3 20 9-9 3 3-9 9z M10 5l4-3 7 7-3 3-4-4-2 2-3-3z',review:'M4 10a8 8 0 0 1 14-5l2 2 M20 3v4h-4 M20 14a8 8 0 0 1-14 5l-2-2 M4 21v-4h4 m1-6 3 3 4-4',bug:'M9 3h6 M10 3v6l-5 10c-1 2 13 2 12 0L14 9V3 M8 14h8 M3 8l3 2 M21 8l-3 2 M11 14v4 M14 15v2'};
const svg = name => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[name] || icons.grid}"/></svg>`;
function hydrate(root=document){root.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=svg(el.dataset.icon));}
hydrate();
const KEY='maxmal-ui-studio-design-v1';
const defaults={left:282,right:404,content:752,font:14,radius:16,bg:'#ffffff',sidebar:'#f9f9f9',text:'#303234',cards:true,logo:true,project:true,copies:{},recent:['帮我看一下本地 Codex的安装情况（cli','你好，为啥我还用不了GPT 6?','你好，分析一下我用不到GPT-6的原因','帮我做一个调研 Deepseek Harness的'],projects:[],model:'5.6 Sol 高'};
let state=structuredClone(defaults);try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved&&typeof saved==='object')state={...state,...saved,copies:{...saved.copies}};}catch{}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{toast('浏览器存储不可用，本次调整仍然有效');}}
const initialCopies={};document.querySelectorAll('[data-copy]').forEach(e=>initialCopies[e.dataset.copy]=e.textContent);
function apply(){for(const key of ['left','right','content','font','radius'])document.documentElement.style.setProperty('--'+key,state[key]+'px');for(const key of ['bg','sidebar','text'])document.documentElement.style.setProperty('--'+key,state[key]);for(const key of ['cards','logo','project'])$('#app').classList.toggle('hide-'+key,!state[key]);document.querySelectorAll('[data-copy]').forEach(e=>e.textContent=state.copies[e.dataset.copy]??initialCopies[e.dataset.copy]??e.textContent);$('#model-label').textContent=state.model;renderRecent();renderProjects();}
const cardLabels=['探索并理解代码','构建新功能、应用或工具','审查代码并提出修改建议','修复问题和失败'];
function renderCards(){const box=$('#cards');box.replaceChildren();cardLabels.forEach((label,i)=>{const b=document.createElement('button');b.type='button';b.className='suggestion';b.innerHTML=svg(['telescope','hammer','review','bug'][i]);const span=document.createElement('span');span.dataset.copy='card'+i;initialCopies['card'+i]=label;span.textContent=state.copies['card'+i]??label;b.append(span);b.onclick=()=>{if(editing)return;$('#prompt').value=span.textContent;$('#prompt').focus();};box.append(b);});}
function renderRecent(filter=''){const root=$('#recent-list');root.replaceChildren();state.recent.filter(t=>t.toLowerCase().includes(filter.toLowerCase())).forEach(t=>{const b=document.createElement('button');b.textContent=t;b.title=t;b.onclick=()=>showConversation(t);root.append(b);});}
function renderProjects(){const root=$('#project-list');root.replaceChildren();$('.empty-project').hidden=state.projects.length>0;state.projects.forEach(p=>{const b=document.createElement('button');b.textContent=p;b.onclick=()=>{$('#selected-project').textContent=p;};root.append(b);});}
let editing=false;let toastTimer;function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2600);}
function modal(title,build){$('#dialog-title').textContent=title;$('#dialog-body').replaceChildren();build($('#dialog-body'));if(!$('#dialog').open)$('#dialog').showModal();}
$('#close-dialog').onclick=()=>$('#dialog').close();$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog')){const r=$('#dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#dialog').close();}});
function choice(root,text,fn){const b=document.createElement('button');b.className='choice';b.textContent=text;b.onclick=fn;root.append(b);return b;}
function note(root,text){const p=document.createElement('p');p.className='note';p.textContent=text;root.append(p);}
function field(root,title,key,type,min,max){const label=document.createElement('label');const span=document.createElement('span');span.textContent=title;const input=document.createElement('input');input.type=type;input.dataset.setting=key;input.setAttribute('aria-label',title);if(type==='checkbox')input.checked=state[key];else input.value=state[key];if(min!==undefined){input.min=min;input.max=max;span.textContent=title+' '+state[key]+'px';}input.oninput=()=>{state[key]=type==='checkbox'?input.checked:type==='range'?Number(input.value):input.value;if(type==='range')span.textContent=title+' '+state[key]+'px';apply();save();};label.append(span,input);root.append(label);}
function settings(){modal('调整界面',root=>{note(root,'调整自动保存在当前浏览器。快捷键 Ctrl / ⌘ + Alt + E 打开此面板。');for(const [t,k,min,max] of [['左栏宽度','left',200,380],['右栏宽度','right',240,520],['内容宽度','content',540,960],['字号','font',12,18],['卡片圆角','radius',0,28]])field(root,t,k,'range',min,max);for(const [t,k] of [['背景','bg'],['左栏背景','sidebar'],['文字颜色','text']])field(root,t,k,'color');for(const [t,k] of [['显示建议卡片','cards'],['显示欢迎图标','logo'],['显示项目选择','project']])field(root,t,k,'checkbox');const actions=document.createElement('div');actions.className='actions';choice(actions,editing?'结束文案编辑':'直接编辑页面文案',()=>{editing=!editing;$('#app').classList.toggle('editing',editing);document.querySelectorAll('[data-copy]').forEach(e=>{e.contentEditable=String(editing);});$('#dialog').close();toast(editing?'点击虚线文字即可修改；按 Esc 结束编辑':'文案已保存');});choice(actions,'编辑最近对话',()=>modal('最近对话',r=>{note(r,'每行一条对话标题。');const ta=document.createElement('textarea');ta.style.width='100%';ta.value=state.recent.join('\n');ta.setAttribute('aria-label','最近对话标题');r.append(ta);choice(r,'保存',()=>{state.recent=ta.value.split('\n').map(s=>s.trim()).filter(Boolean);save();renderRecent();$('#dialog').close();});}));choice(actions,'导出设计配置',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='maxmal-ui-design.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});choice(actions,'恢复参考布局',()=>{state=structuredClone(defaults);save();renderCards();apply();$('#selected-project').textContent='选择项目';$('#app').classList.remove('no-left','no-right','mobile-left','mobile-right');$('#dialog').close();toast('已恢复参考布局');});root.append(actions);});}
document.addEventListener('input',e=>{if(e.target.matches('[data-copy]')&&editing){state.copies[e.target.dataset.copy]=e.target.textContent;save();}});
function showConversation(text){$('.welcome').hidden=true;const box=$('#conversation');box.hidden=false;const user=document.createElement('div');user.className='message user';user.textContent=text;const response=document.createElement('div');response.className='message assistant';const label=document.createElement('small');label.textContent='界面演示';const content=document.createElement('div');content.textContent='我们可以从这里开始。\n\n这条回复用于预览对话的排版、间距和输入体验。你可以继续输入，或通过左下角的帮助按钮调整界面。';response.append(label,content);box.append(user,response);box.scrollTop=box.scrollHeight;}
$('#composer').onsubmit=e=>{e.preventDefault();const text=$('#prompt').value.trim();if(!text){toast('输入一条消息，预览对话效果');return;}showConversation(text);state.recent=[text,...state.recent.filter(t=>t!==text)].slice(0,30);save();renderRecent();$('#prompt').value='';$('#attachments').replaceChildren();};$('#prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('#composer').requestSubmit();}};
function tool(kind){const preview=$('.tool-preview');const opened=preview.dataset.kind===kind&&!preview.hidden;preview.hidden=opened;$('.tool-shortcuts').hidden=!opened;preview.dataset.kind=kind;preview.replaceChildren();if(opened)return;const close=choice(preview,'← 返回工具',()=>{preview.hidden=true;$('.tool-shortcuts').hidden=false;});close.style.marginBottom='20px';const h=document.createElement('h3');h.textContent=kind==='browser'?'浏览器':'终端';preview.append(h);if(kind==='browser'){const input=document.createElement('input');input.placeholder='输入网址';input.setAttribute('aria-label','预览网址');preview.append(input);const p=document.createElement('p');p.textContent='浏览器预览区域';preview.append(p);input.onkeydown=e=>{if(e.key==='Enter')p.textContent='本地界面预览：'+input.value;};}else{const pre=document.createElement('pre');pre.textContent='$ welcome\n终端界面演示\n\n~/project › ';preview.append(pre);const input=document.createElement('input');input.placeholder='输入演示命令';input.setAttribute('aria-label','演示命令');preview.append(input);input.onkeydown=e=>{if(e.key==='Enter'){pre.textContent+='\n› '+input.value+'\n（仅展示输入，不执行命令）';input.value='';}};}}
const actions={settings,new:()=>{$('.welcome').hidden=false;$('#conversation').hidden=true;$('#conversation').replaceChildren();$('#prompt').value='';$('#prompt').focus();},left:()=>{if(innerWidth<=620)$('#app').classList.toggle('mobile-left');else $('#app').classList.toggle('no-left');},right:()=>{if(innerWidth<=960)$('#app').classList.toggle('mobile-right');else $('#app').classList.toggle('no-right');},focus:()=>{const on=!$('#app').classList.contains('no-right');$('#app').classList.toggle('no-left',on);$('#app').classList.toggle('no-right',on);},model:()=>modal('选择模型',r=>{['5.6 Sol 高','GPT-6 高','5.6 Sol 中','自定义模型'].forEach(m=>choice(r,m,()=>{if(m==='自定义模型'){modal('自定义模型',root=>{const input=document.createElement('input');input.placeholder='模型名称';input.setAttribute('aria-label','模型名称');root.append(input);choice(root,'应用',()=>{if(input.value.trim()){state.model=input.value.trim();save();apply();$('#dialog').close();}});});}else{state.model=m;save();apply();$('#dialog').close();}}));}),approval:()=>modal('批准方式',r=>{['请求批准','自动批准','只读模式'].forEach(t=>choice(r,t,()=>{$('#approval-label').textContent=t;$('#dialog').close();}));}),project:()=>modal('选择项目',r=>{state.projects.forEach(p=>choice(r,p,()=>{$('#selected-project').textContent=p;$('#dialog').close();}));const input=document.createElement('input');input.placeholder='新项目名称';input.setAttribute('aria-label','新项目名称');r.append(input);choice(r,'添加演示项目',()=>{const v=input.value.trim();if(v){if(!state.projects.includes(v))state.projects.push(v);save();renderProjects();$('#selected-project').textContent=v;$('#dialog').close();}});}),search:()=>modal('搜索对话',r=>{const input=document.createElement('input');input.placeholder='搜索最近对话';input.setAttribute('aria-label','搜索最近对话');input.style.width='100%';r.append(input);const list=document.createElement('div');r.append(list);function search(){list.replaceChildren();state.recent.filter(t=>t.includes(input.value)).forEach(t=>choice(list,t,()=>{showConversation(t);$('#dialog').close();}));if(!list.children.length)note(list,'没有匹配的对话');}input.oninput=search;search();}),attach:()=>$('#file').click(),browser:()=>tool('browser'),terminal:()=>tool('terminal'),notifications:()=>modal('通知',r=>note(r,'暂无新通知')),profile:settings,voice:()=>toast('语音界面演示，未接入语音服务'),mic:()=>toast('麦克风界面演示，未请求录音权限'),back:()=>actions.new(),forward:()=>{if(state.recent[0])showConversation(state.recent[0]);}};
for(const [k,title] of [['pull','拉取请求'],['sites','站点'],['scheduled','已安排'],['plugins','插件']])actions[k]=()=>modal(title,r=>note(r,'暂无内容。此区域用于展示「'+title+'」的页面入口。'));
document.addEventListener('click',e=>{if(editing&&e.target.closest('[data-copy]')){e.preventDefault();return;}const b=e.target.closest('[data-action]');if(b)actions[b.dataset.action]?.();});
$('#file').onchange=()=>{for(const file of $('#file').files){const b=document.createElement('button');b.type='button';b.textContent=file.name+' ×';b.title='移除附件';b.onclick=()=>b.remove();$('#attachments').append(b);}$('#file').value='';};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.altKey&&e.key.toLowerCase()==='e'){e.preventDefault();settings();}if(e.key==='Escape'&&editing){editing=false;$('#app').classList.remove('editing');document.querySelectorAll('[data-copy]').forEach(el=>el.contentEditable='false');toast('文案已保存');}});
for(const side of ['left','right']){const el=$('.resize-'+side);el.onpointerdown=e=>{e.preventDefault();el.setPointerCapture(e.pointerId);const x=e.clientX;const start=parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--'+side));let value=start;const move=event=>{value=Math.round(Math.max(side==='left'?200:240,Math.min(side==='left'?380:520,start+(event.clientX-x)*(side==='left'?1:-1))));document.documentElement.style.setProperty('--'+side,value+'px');};const stop=()=>{state[side]=value;save();el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',stop);el.removeEventListener('pointercancel',stop);};el.addEventListener('pointermove',move);el.addEventListener('pointerup',stop);el.addEventListener('pointercancel',stop);};el.onkeydown=e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const delta=(e.key==='ArrowRight'?10:-10)*(side==='left'?1:-1);state[side]=Math.max(side==='left'?200:240,Math.min(side==='left'?380:520,state[side]+delta));apply();save();};}
renderCards();apply();
